# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
