# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_calendar', '0003_auto_20170227_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
