# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_calendar', '0004_publication_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='substituted_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simply_posted_calendar.Publication'),
        ),
    ]
