# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-05 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_report_project_id', models.CharField(max_length=50)),
                ('social_report_user_id', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('business_type', models.CharField(max_length=50)),
                ('market_type', models.CharField(max_length=50)),
                ('temp_type', models.CharField(max_length=50)),
                ('about_business', models.CharField(max_length=100)),
                ('about_topics', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simply Posted Customer Profiles',
                'verbose_name_plural': 'Simply Posted Customer Profiles',
            },
        ),
    ]
