# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.CharField(help_text='Enter the your email name', max_length=50, verbose_name='email')),
                ('password', models.CharField(help_text='Enter the discount (max 100)', max_length=80, verbose_name='discount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
