# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-02 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_accounts', '0002_contentprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprovider',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
