# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-04 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_accounts', '0007_auto_20170302_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentprovider',
            name='customer_id',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
