# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-06 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_accounts', '0008_contentprovider_customer_id'),
    ]

    operations = [
        migrations.RenameModel('DBform', 'Post')
    ]
