# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-06 13:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0006_partial'),
        ('simply_posted_accounts', '0009_auto_20170306_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('social_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
            ],
        ),
    ]
