# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-07 15:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_accounts', '0011_post_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_categories',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
