# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_accounts', '0012_userprofile_selected_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='social_auth',
        ),
        migrations.DeleteModel(
            name='SocialProfile',
        ),
    ]
