# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simply_posted_accounts', '0014_rejectedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedpost',
            name='users',
            field=models.ManyToManyField(related_name='rejected_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
